name: Maven

on:
  workflow_call:
    inputs:
      maven-goal:
        description: 'Maven goal to run'
        required: true
        default: 'package'
        type: string

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: build
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - uses: whelk-io/maven-settings-xml-action@v22
        with:
          servers: '[{ "id":"dvsa-github-packages", "configuration": { "httpHeaders": { "property": { "name":"Authorization", "value":"Bearer ${{ secrets.GITHUB_TOKEN }}"} } } },{ "id":"github", "configuration": { "httpHeaders": { "property": { "name":"Authorization", "value":"Bearer ${{ secrets.GITHUB_TOKEN }}"} } } } ]'

      - run: mvn -B ${{ inputs.maven-goal }}